# Generated by Django 4.2.30 on 2026-07-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('atendida', models.BooleanField(default=False, verbose_name='atendida')),
                ('dias_estimados_agotamiento', models.PositiveIntegerField(blank=True, null=True, verbose_name='dias estimados hasta agotamiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='products.producto')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ['-fecha'],
            },
        ),
    ]
