# Generated by Django 4.2.30 on 2026-07-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='unidad de medida')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio de compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio de venta')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='stock actual')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='stock minimo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.categoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
    ]
