# Generated by Django 4.2.30 on 2026-07-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10, verbose_name='tipo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='costo unitario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='products.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='suppliers.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='users.usuario')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
