# Generated by Django 4.2.30 on 2026-07-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('contacto', models.CharField(blank=True, max_length=150, verbose_name='contacto')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='direccion')),
                ('condiciones_pago', models.CharField(blank=True, max_length=200, verbose_name='condiciones de pago')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
