# Generated by Django 4.2.30 on 2026-07-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='clave')),
                ('valor', models.CharField(blank=True, max_length=255, verbose_name='valor')),
            ],
            options={
                'verbose_name': 'configuracion del sistema',
                'verbose_name_plural': 'configuraciones del sistema',
                'ordering': ['clave'],
            },
        ),
    ]
